// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_varpropTMB_TMBExports
#include <TMB.hpp>
#include "dsm.hpp"
#include "chooseNLL.hpp"


template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "dsm") {
    return dsm(this);
  } else if(model == "chooseNLL") {
    return chooseNLL(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
